artifact_location: file:///C:/Users/Администратор/Desktop/dust_detection_project/runs/mlflow/976810576888416561
creation_time: 1715937022501
experiment_id: '976810576888416561'
last_update_time: 1715937022501
lifecycle_stage: active
name: /Shared/YOLOv8
