stages:
  preprocess:
    cmd: python preprocessing/preprocess_data.py
    deps:
      - real_time_detection/camera_config.json
      - preprocessing/preprocess_data.py
    outs:
      - preprocessed_data/  # Output directory for preprocessed data

  train:
    cmd: python Research/training_script/train.py
    deps:
      - data/  # Ensures it uses the data directory
      - preprocessed_data/  # Uses the output of the preprocess stage
      - Research/training_script/train.py
      - real_time_detection/utils.py
      - Research/params.yaml
    outs:
      - models/best.pt  # Best model output
      - reports/train_params.yaml:  # Training parameters output
          cache: false
    metrics:
      - reports/train_metrics.csv:  # Training metrics output
          cache: false

  deploy:
    cmd: python deployment/deploy_model.py
    deps:
      - models/best.pt
      - deployment/deploy_model.py
    outs:
      - models/deployed_model.pt  # Deployed model output

  inference:
    cmd: python real_time_detection/inference.py
    deps:
      - models/deployed_model.pt
      - real_time_detection/camera_config.json
      - real_time_detection/inference.py
    outs:
      - saved_frames/  # Directory for saved frames
