model_type: yolov8m.pt 
pretrained: True
seed: 0
imgsz: 640 
batch: 8 
epochs: 25
optimizer: SGD # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.01  # learning rate 
name: 'yolov8m_exp_v0' # experiment name