artifact_location: file:///C:/Users/Администратор/Desktop/dust_detection_project/runs/mlflow/0
creation_time: 1715937022398
experiment_id: '0'
last_update_time: 1715937022398
lifecycle_stage: active
name: Default
